"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga backend/.env si existe (no se versiona; ver .env.example). En
# desarrollo, sin .env, todas las variables caen a los defaults de abajo.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
#
# Las sesiones se firman con esta clave (SESSION_ENGINE = signed_cookies),
# así que quien la conozca puede fabricarse una sesión de cualquier
# usuario. Por eso, con DEBUG=False, arrancar sin DJANGO_SECRET_KEY es un
# error duro: es preferible que el despliegue falle a que se levante
# firmando sesiones con una clave pública que está en el repositorio.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY es obligatorio con DJANGO_DEBUG=False. '
            'Genera una con:\n'
            "  python -c \"from django.core.management.utils import "
            'get_random_secret_key as g; print(g())"',
        )
    SECRET_KEY = 'django-insecure-solo-para-desarrollo-local-no-usar-en-produccion'

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get(
        'DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,10.0.2.2',
    ).split(',') if h.strip()
]

# Render publica el dominio asignado en esta variable. Se añade solo para
# no tener que copiarlo a mano tras el primer despliegue (y porque el
# dominio no se conoce hasta que el servicio existe).
_dominio_render = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _dominio_render and _dominio_render not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_dominio_render)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
    'users',
    'trips',
    'negotiation',
    'ratings',
]

# CORS. La app Android no envía cabecera Origin, así que esto solo afecta
# a la versión web. Abrir a todos los orígenes con credenciales activas
# permitiría a cualquier página robar sesiones, por eso en producción se
# exige la lista explícita de dominios.
CORS_ALLOW_CREDENTIALS = True
_origenes = os.environ.get('DJANGO_CORS_ORIGINS', '').strip()
if _origenes:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _origenes.split(',') if o.strip()]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DJANGO_CORS_ORIGINS es obligatorio con DJANGO_DEBUG=False. '
            'Indica los orígenes permitidos separados por coma, por ejemplo: '
            'https://motolink.example.com',
        )
    # Solo en desarrollo: permite `flutter run -d chrome`, que usa un
    # puerto distinto en cada arranque.
    CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.SesionUsuarioAuthentication',
    ],
    # IsAuthenticated por defecto: toda ruta exige sesión salvo que
    # declare lo contrario. Antes el default era AllowAny, y como el actor
    # (pasajero_id, conductor_id) viajaba en el cuerpo de la petición,
    # cualquiera podía suplantar a otro usuario o borrar cuentas.
    # Las excepciones son el registro y el login, marcados con AllowAny.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Freno a la fuerza bruta contra el login y al alta masiva de cuentas.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',          # por cuenta atacada
        'login_origen': '30/min',   # por origen, más holgado
        'registro': '20/hour',
    },
    # Detrás del proxy de Render la IP real del cliente llega en
    # X-Forwarded-For. Sin este ajuste DRF usa la cabecera entera, y si la
    # cadena de proxies varía cada petición cae en un contador distinto:
    # así fue como el límite del login dejó de aplicarse en producción
    # mientras seguía funcionando en local.
    'NUM_PROXIES': int(os.environ.get('DJANGO_NUM_PROXIES', '1')),
    # Por defecto DRF serializa DecimalField como string (ej. "9.00") para
    # no perder precisión. El cliente Dart espera num en tarifas (tarifa_propuesta,
    # tarifa_final, tarifa de Oferta); con el valor por defecto el cast
    # `as num` fallaba en runtime y dejaba pantallas cargando indefinidamente.
    'COERCE_DECIMAL_TO_STRING': False,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los estáticos en producción sin necesitar nginx.
    # Sin él, la interfaz navegable de DRF sale sin estilos al desplegar.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Base de datos
#
# Los datos de MotoLink (usuarios, mototaxistas, solicitudes, viajes,
# ofertas y calificaciones) viven en Cloud Firestore, no aquí. El acceso
# va por los repositorios de core.firestore; ver core/di.py.
#
# La entrada 'default' queda solo para la infraestructura del propio
# Django (admin, auth, contenttypes). Ninguna petición de la API la toca:
# las sesiones se firman en cookie (SESSION_ENGINE, más abajo).

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Backend de documentos: 'firestore' (producción y desarrollo normal) o
# 'memory' (tests y demos sin credenciales). Ver core/firestore/registry.py.
MOTOLINK_DB_BACKEND = os.environ.get('MOTOLINK_DB_BACKEND', 'firestore')
os.environ.setdefault('MOTOLINK_DB_BACKEND', MOTOLINK_DB_BACKEND)

# Credencial del Admin SDK. Es un secreto real: nunca se versiona.
# Descargarla en la consola de Firebase > Configuración del proyecto >
# Cuentas de servicio > Generar nueva clave privada.
FIREBASE_CREDENTIALS_FILE = os.environ.get('FIREBASE_CREDENTIALS_FILE', '')
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', '')

# Sesiones firmadas en cookie: no necesitan tabla django_session, así que
# el login tampoco depende de SQL.
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# La cookie de sesión no debe ser legible desde JavaScript.
SESSION_COOKIE_HTTPONLY = True
# Cierra la sesión a los 7 días aunque el usuario no haga logout.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7

# Endurecimiento para cuando el backend queda expuesto a internet. En
# desarrollo local queda desactivado, porque no hay TLS y forzar cookies
# "secure" impediría iniciar sesión sobre http://.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # 1 año, pero se arranca con un valor bajo si es la primera vez: HSTS
    # es difícil de revertir si el dominio aún no sirve HTTPS estable.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', 3600))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Detrás de nginx o de un PaaS, la petición llega por http al proceso;
    # esta cabecera es la que le dice a Django que el cliente sí usó TLS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # La app móvil manda la cookie desde su propio origen.
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_TRUSTED_ORIGINS = [
        o for o in os.environ.get('DJANGO_CORS_ORIGINS', '').split(',') if o.strip()
    ]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Destino de `collectstatic`, que se ejecuta en cada despliegue.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
