# Generated by Django 5.2.15 on 2026-06-21 00:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudViaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('tarifa_propuesta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enNegociacion', 'En negociación'), ('aceptada', 'Aceptada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_viaje', to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tarifa_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('enCurso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='asignado', max_length=20)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_como_conductor', to='users.mototaxista')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_como_pasajero', to='users.usuario')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viaje', to='trips.solicitudviaje')),
            ],
        ),
    ]
