# Generated by Django 5.2.15 on 2026-06-21 00:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(choices=[('aceptacion', 'Aceptación'), ('contraoferta', 'Contraoferta'), ('rechazo', 'Rechazo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='users.mototaxista')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='trips.solicitudviaje')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('solicitud', 'conductor'), name='un_conductor_por_solicitud')],
            },
        ),
    ]
