# Generated by Django 5.2.15 on 2026-06-21 00:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('pasajero', 'Pasajero'), ('mototaxista', 'Mototaxista'), ('administrador', 'Administrador')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mototaxista',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mototaxista', serialize=False, to='users.usuario')),
                ('licencia', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=20)),
                ('marca_vehiculo', models.CharField(max_length=50)),
                ('modelo_vehiculo', models.CharField(max_length=50)),
            ],
        ),
    ]
